📘 Notebook 04 — Feature Engineering

In [3]:
import pandas as pd

df = pd.read_csv("../data/processed/sales_clean.csv")
df.head()

,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,state,...,sales,quantity,profit,returns,payment_mode,profit_margin,year,month,month_name,customer_segment
0,CA-2019-160304,2019-01-01,2019-07-01,Standard Class,BM-11575,Brendan Murry,Corporate,United States,Gaithersburg,Maryland,...,73.94,1,28.2668,No,Online,0.382294,2019,1,January,Regular
1,CA-2019-160304,2019-02-01,2019-07-01,Standard Class,BM-11575,Brendan Murry,Corporate,United States,Gaithersburg,Maryland,...,173.94,3,38.2668,No,Online,0.220000,2019,2,February,Regular
2,CA-2019-160304,2019-02-01,2019-07-01,Standard Class,BM-11575,Brendan Murry,Corporate,United States,Gaithersburg,Maryland,...,231.98,2,67.2742,No,Cards,0.290000,2019,2,February,Regular
3,CA-2019-125206,2019-03-01,2019-05-01,First Class,LR-16915,Lena Radford,Consumer,United States,Los Angeles,California,...,114.46,2,28.6150,No,Online,0.250000,2019,3,March,Regular
4,US-2019-116365,2019-03-01,2019-08-01,Standard Class,CA-12310,Christine Abelman,Corporate,United States,San Antonio,Texas,...,30.08,2,-5.2640,No,Online,-0.175000,2019,3,March,Regular

In [4]:
df["profit_margin"] = df["profit"] / df["sales"]

In [5]:
df["order_date"] = pd.to_datetime(df["order_date"], errors="coerce")

In [6]:
df["year"] = df["order_date"].dt.year

In [7]:
df["month"] = df["order_date"].dt.month

In [8]:
df["month_name"] = df["order_date"].dt.month_name()

3️⃣ Customer Segments (تقسيم العملاء)

In [9]:
customer_orders = df.groupby("customer_id")["order_id"].count()

df["customer_segment"] = df["customer_id"].map(
    lambda x: "VIP" if customer_orders[x] >= 10 else "Regular"
)

In [10]:
df.head()

,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,state,...,sales,quantity,profit,returns,payment_mode,profit_margin,year,month,month_name,customer_segment
0,CA-2019-160304,2019-01-01,2019-07-01,Standard Class,BM-11575,Brendan Murry,Corporate,United States,Gaithersburg,Maryland,...,73.94,1,28.2668,No,Online,0.382294,2019,1,January,Regular
1,CA-2019-160304,2019-02-01,2019-07-01,Standard Class,BM-11575,Brendan Murry,Corporate,United States,Gaithersburg,Maryland,...,173.94,3,38.2668,No,Online,0.220000,2019,2,February,Regular
2,CA-2019-160304,2019-02-01,2019-07-01,Standard Class,BM-11575,Brendan Murry,Corporate,United States,Gaithersburg,Maryland,...,231.98,2,67.2742,No,Cards,0.290000,2019,2,February,Regular
3,CA-2019-125206,2019-03-01,2019-05-01,First Class,LR-16915,Lena Radford,Consumer,United States,Los Angeles,California,...,114.46,2,28.6150,No,Online,0.250000,2019,3,March,Regular
4,US-2019-116365,2019-03-01,2019-08-01,Standard Class,CA-12310,Christine Abelman,Corporate,United States,San Antonio,Texas,...,30.08,2,-5.2640,No,Online,-0.175000,2019,3,March,Regular

In [11]:
# remove wrong margin if exists
df = df.drop(columns=["profit_margin"], errors="ignore")

In [15]:
# recalculate correctly
df = df[df["sales"] > 0]
df["profit_margin"] = (df["profit"] / df["sales"]) * 100

In [17]:
df = df[df["sales"] > 10]  # threshold منطقي

In [18]:
df.to_csv("../data/processed/sales_clean.csv", index=False)